
export const SET_CANDIDATES = 'SET_CANDIDATES'
export const REMOVE_CANDIDATE = 'REMOVE_CANDIDATE'
export const SORT_CANDIDATES = 'SORT_CANDIDATES'
export const RESET_ATTRIBUTE_SORTING = 'RESET_ATTRIBUTE_SORTING'
export const TOGGLE_ATTRIBUTE_GROUPING = 'TOGGLE_ATTRIBUTE_GROUPING'
export const RESIZE_ATTRIBUTE = 'RESIZE_ATTRIBUTE'
export const REMOVE_ATTRIBUTE = 'REMOVE_ATTRIBUTE'
export const RESTORE_ATTRIBUTE = 'RESTORE_ATTRIBUTE'

export const TOGGLE_RANKING_TEXT = 'TOGGLE_SHOW_RANKING_TEXT'
export const TOGGLE_RANKING_FILTER = 'TOGGLE_RANKING_FILTER'
export const SET_ATTRIBUTE_FILTER_RANGE = 'SET_ATTRIBUTE_FILTER_RANGE'
export const APPLY_ATTRIBUTE_FILTER = 'APPLY_ATTRIBUTE_FILTER'
export const RESET_ATTRIBUTE_FILTER = 'RESET_ATTRIBUTE_FILTER'
export const RESET_ATTRIBUTE_FILTERS = 'RESET_ATTRIBUTE_FILTERS'
export const COMMIT_ATTRIBUTE_FILTER = 'COMMIT_ATTRIBUTE_FILTER'
export const SELECT_ATTRIBUTE_FILTER_OPTION = 'SELECT_ATTRIBUTE_FILTER_OPTION'
export const ADD_CANDIDATE_FILTER = 'ADD_CANDIDATE_FILTER'
export const DELETE_CANDIDATE_FILTER = 'DELETE_CANDIDATE_FILTER'
export const APPLY_CANDIDATE_FILTERS = 'APPLY_CANDIDATE_FILTERS'

export const INITIALIZE_CANDIDATE_ATTRIBUTE = 'INITIALIZE_CANDIDATE_ATTRIBUTE'
export const UPDATE_CANDIDATE_ATTRIBUTE = 'UPDATE_CANDIDATE_ATTRIBUTE'
export const ADD_CANDIDATE_ATTRIBUTE = 'ADD_CANDIDATE_ATTRIBUTE'
export const ADD_CANDIDATE = 'ADD_CANDIDATE';
export const MOCK_STORE = 'MOCK_STORE';

export const SET_ALGORITHM_BUDGET = 'SET_ALGORITHM_BUDGET';
export const SET_MAX_BUDGET = 'SET_MAX_BUDGET';
export const RETRIEVE_PLAN = 'RETRIEVE_PLAN';
export const SET_BUDGET_PROVENANCE = 'SET_BUDGET_PROVENANCE';
export const INITIALIZE_PLAN = 'INITIALIZE_PLAN';

export const RESET_WEIGHT = "RESET_WEIGHT";


export const EDIT_PLAN_BY_EDGE = "EDIT_PLAN_BY_EDGE";
export const SELECT_AN_EDGE = "SELECT_AN_EDGE";
export const ADD_CANDIDATE_PLAN = "ADD_CANDIDATE_PLAN";
export const CHANGE_COMPARISON_MODAL_VISIBILITY = "CHANGE_COMPARISON_MODAL_VISIBILITY";
export const MERGE_PLAN_CANDIDATE="MERGE_PLAN_CANDIDATE";
export const Set_Current_Merging_Sequence="SetCurrentMergingSequence";
export const SELECT_PLAN_FOR_MERGING="SELECT_PLAN_FOR_MERGING";
export const CONFIRM_ALGORITHM_BUDGET="CONFIRM_ALGORITHM_BUDGET";
export const SET_REGION_BOUNDARY="SET_REGION_BOUNDARY";
export const SET_COMPARISON_MAP_PLAN="SET_COMPARISON_MAP_PLAN";
export const EXTEND_POI_LIST="EXTEND_POI_LIST";
export const SET_POI_TYPE_DISPLAY="SET_POI_TYPE_DISPLAY";
export const MERGE_CANDIDATE_PLANS="MERGE_CANDIDATE_PLANS";
export const REMOVE_CANDIDATE_PLAN="REMOVE_CANDIDATE_PLAN";
export const UPDATE_ATTRIBUTES="UPDATE_ATTRIBUTES";
export const SET_POI_POS="SET_POI_POS";
